### PR TITLE
codec: add new_with_codec method to codec context

### PR DESCRIPTION
**Pull request by sergeymolchanov**
Wrapper for "avcodec_alloc_context3" with not-null codec is needed when you dont use output stream, so you cant pass a codec to "add_stream" method

### CODE REVIEW

**Comment by bee-mo** [comment]
You might want to pass the codec by reference to not pass ownership

**Comment by SnyderTheOne** [comment]
@sergeymolchanov With this change, where you able to get the x264-transcoding example working with FFMPEG 5.0+?

**Comment by Polochon-street** [comment]
closing, since the functionality has been merged :)

**Comment by brandonros** [comment]
@Polochon-street thank you for doing this. you forgot to close this one by the way, thank you

**Comment by Polochon-street** [comment]
oh, right, thanks for telling me, closing for real :D

**Pull request closed without merging**
