### PR TITLE
Using non-windows-only error consts only on non-windows platforms

### PR DESCRIPTION
**Pull request by kmaork**
Hey! I'm planning to use this project on windows. Before this change it didn't compile, and now it does :)

### CODE REVIEW

**Comment by zmwangx** [comment]
Oh, I took a look at https://docs.microsoft.com/en-us/cpp/c-runtime-library/errno-constants?view=vs-2019, saw that POSIX errnos are supported for compatibility, so didn't check if all are actually available.

Since those three are reserved in POSIX, I'm simply dropping those. I took the liberty to modify the commit that way. Merged in 6a7a69e1e7d6d86a09f6360bd973ff249df46f89 (authorship still yours).

**Comment by zmwangx** [comment]
I'll add a Windows build to the CI shortly to avoid breaking Windows compatibility in the future.

**Comment by kmaork** [comment]
Amazing, thanks!

**Comment by zmwangx** [comment]
Windows build added, and released v4.3.6 including this fix.

**Pull request closed without merging**
