### PR TITLE
remove filter::Context generic lifetime parameter

### PR DESCRIPTION
**Pull request by VincentJousse**
issue #193

### CODE REVIEW

**Comment by VincentJousse** [comment]
Done ;)

**Comment by Polochon-street** [comment]
Would you rebase again? There were new clippy errors, seems that rust updates faster than I can fix lints...

**Comment by VincentJousse** [comment]
@Polochon-street  Done again !

**Comment by Polochon-street** [comment]
thanks!

**Comment by VincentJousse** [comment]
@Polochon-street just a reminder : this MR breaks the API !! Do you plan any release soon ?

**Comment by Polochon-street** [comment]
Unfortunately, that crate doesn't follow semver, so I can only release minor versions (otherwise the build script will try and fetch e.g. ffmpegv7.1 as far as I remember). I'll release a new version now :)

**Comment by Polochon-street** [comment]
it should be released now.

**Pull request merged**
