### PR TITLE
Add ffmpeg 6.0 support

### PR DESCRIPTION
**Pull request by AdrianEddy**
Even though 6.0 is not officially released yet, the API changes are frozen and releases/6.0 is branched.
This PR adds support for the 6.0 branch

Depends on https://github.com/zmwangx/rust-ffmpeg-sys/pull/50

### CODE REVIEW

**Comment by Polochon-street** [comment]
hi! Thanks for submitting.

I just added a CI check for ffmpeg 6 on linux, and fixed the linting errors. Could you rebase on master so we can make sure everything runs? :)

**Comment by Polochon-street** [comment]
seems like running `cargo fmt` is needed - and the early builds (https://github.com/zmwangx/rust-ffmpeg/actions/runs/4406469929/jobs/7722112144 for instance) are failing because of discrepancies between ffmpeg5 and before. Maybe conditional compilation statements could be used to fix the build for earlier versions?

**Comment by AdrianEddy** [comment]
Please check now

**Comment by AdrianEddy** [comment]
Sorry, it actually looks like feature ffmpeg_6_0 is not included because the version check is wrong, please merge https://github.com/zmwangx/rust-ffmpeg-sys/pull/54

**Comment by Polochon-street** [comment]
done, it should be published at `rust-ffmpeg-sys` 6.0.1 :)

**Comment by AdrianEddy** [comment]
Updated the dependency to 6.0.1

**Comment by Polochon-street** [comment]
perfect, thank you! Merging.

**Pull request merged**
